# Generated by Django 3.2.12 on 2024-05-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20240513_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={},
        ),
        migrations.RemoveField(
            model_name='notes',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
